### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by patrickcapadmi** [Worldpay/access-checkout-ios#168]
The Access Checkout Android repo has a [license](https://github.com/Worldpay/access-checkout-android/blob/master/LICENSE) included but there isn't one included with the iOS SDK. Can that be added in for the next release?

**Comment by ochalet-wp** [comment]
Hi, thank you for raising that. The license file exists but it is located in the [AccessCheckoutSDK](https://github.com/Worldpay/access-checkout-ios/tree/master/AccessCheckoutSDK) folder. 
We will move it to the root of the repo for clarity.
